### ISSUE TITLE
easier setup

### ISSUE THREAD

**Issue by marcb4** [tmxs/ImageSorter#1]
just a quick and easy way to install
use
`curl -s https://raw.githubusercontent.com/tmxs/ImageSorter/master/install.sh | bash`
instead of downloading it and execute it with 
```
curl -LO https://raw.githubusercontent.com/tmxs/ImageSorter/master/install.sh
sh ./install.sh
```

**Comment by tmxs** [comment]
Thanks for the hint, i have applied your recommendation :)
